import XCTest
@testable import PoolPlanner

/// Parity tests against fixtures generated by running the web app's own
/// JavaScript geometry (scratchpad gen-fixtures.mjs copies index.html's
/// functions verbatim). Tolerances: sub-millimeter for meters, ~1e-12 deg
/// for coordinates.
final class GeometryParityTests: XCTestCase {
    struct Fixtures: Decodable {
        struct Projection: Decodable { let ref, ll, back: LatLng; let xy: XY }
        struct Segment: Decodable { let p, a, b: XY; let dist: Double; let closest: XY }
        struct PIP: Decodable { let poly: [XY]; let pt: XY; let inside: Bool }
        struct Area: Decodable { let ptsLL: [LatLng]; let areaM2: Double }
        struct Shape: Decodable {
            let c: LatLng
            let wFt, lFt, rot, aM, bM: Double
            let shape: String
            let pts: [LatLng]
        }
        struct Compliance: Decodable {
            struct Edge: Decodable { let edgeIndex: Int; let d: Double; let from, to: XY }
            struct Gap: Decodable { let d: Double; let from, to: XY }
            let center: LatLng
            let shape: String
            let wFt, lFt, rot: Double
            let lotLL: [LatLng]
            let structLL: [LatLng]
            let equipLL: LatLng
            let nearestLotEdges: [Edge]
            let insideLot: Bool
            let nearestStructure: Gap
            let equipToPool, equipToLot, lotAreaM2, poolFootprintM2, coveragePct: Double
        }
        struct Round: Decodable { let x, rounded: Double }
        let projection: [Projection]
        let segments: [Segment]
        let pointInPoly: [PIP]
        let polygonArea: [Area]
        let shapes: [Shape]
        let compliance: Compliance
        let round05: [Round]
    }

    static let fixtures: Fixtures = {
        let url = Bundle(for: GeometryParityTests.self)
            .url(forResource: "parity", withExtension: "json")!
        return try! JSONDecoder().decode(Fixtures.self, from: Data(contentsOf: url))
    }()

    var f: Fixtures { Self.fixtures }

    private let mTol = 1e-6 // meters
    private let degTol = 1e-12 // degrees

    func testProjectionRoundTrips() {
        for c in f.projection {
            let xy = Geo.llToXY(c.ll, ref: c.ref)
            XCTAssertEqual(xy.x, c.xy.x, accuracy: mTol)
            XCTAssertEqual(xy.y, c.xy.y, accuracy: mTol)
            let back = Geo.xyToLL(xy, ref: c.ref)
            XCTAssertEqual(back.lat, c.back.lat, accuracy: degTol)
            XCTAssertEqual(back.lng, c.back.lng, accuracy: degTol)
        }
    }

    func testSegmentDistances() {
        for c in f.segments {
            XCTAssertEqual(Geo.distPointSeg(c.p, c.a, c.b), c.dist, accuracy: mTol)
            let r = Geo.closestPtSeg(c.p, c.a, c.b)
            XCTAssertEqual(r.c.x, c.closest.x, accuracy: mTol)
            XCTAssertEqual(r.c.y, c.closest.y, accuracy: mTol)
        }
    }

    func testPointInPoly() {
        for c in f.pointInPoly {
            XCTAssertEqual(Geo.pointInPoly(c.pt, c.poly), c.inside, "\(c.pt)")
        }
    }

    func testPolygonArea() {
        for c in f.polygonArea {
            XCTAssertEqual(Geo.polygonAreaM2(c.ptsLL), c.areaM2, accuracy: 1e-4)
        }
    }

    func testShapePoints() {
        for c in f.shapes {
            let kind = PoolShapeKind(rawValue: c.shape)!
            let pts = PoolShape.points(center: c.c, aM: c.aM, bM: c.bM, rotDeg: c.rot, shape: kind)
            XCTAssertEqual(pts.count, c.pts.count)
            for (got, want) in zip(pts, c.pts) {
                XCTAssertEqual(got.lat, want.lat, accuracy: degTol)
                XCTAssertEqual(got.lng, want.lng, accuracy: degTol)
            }
        }
    }

    func testComplianceScenarioMatchesWebApp() {
        let c = f.compliance
        let kind = PoolShapeKind(rawValue: c.shape)!
        let aM = c.lFt * Geo.metersPerFoot / 2
        let bM = c.wFt * Geo.metersPerFoot / 2
        let ring = PoolShape.points(center: c.center, aM: aM, bM: bM, rotDeg: c.rot, shape: kind)
        let site = SiteGeometry(
            poolCenter: c.center,
            poolRing: ring,
            poolFootprintM2: PoolShape.footprintM2(aM: aM, bM: bM, shape: kind),
            lot: c.lotLL,
            structures: [c.structLL],
            equipment: [c.equipLL]
        )
        let report = ComplianceEngine.evaluate(site: site, rules: .example)

        XCTAssertEqual(report.poolCenterInsideLot, c.insideLot)

        // two nearest lot edges match the web's connectors
        XCTAssertGreaterThanOrEqual(report.lotEdgeGaps.count, 2)
        for (got, want) in zip(report.lotEdgeGaps.prefix(2), c.nearestLotEdges) {
            XCTAssertEqual(got.edgeIndex, want.edgeIndex)
            XCTAssertEqual(got.connector.d, want.d, accuracy: mTol)
            XCTAssertEqual(got.connector.from.x, want.from.x, accuracy: mTol)
            XCTAssertEqual(got.connector.from.y, want.from.y, accuracy: mTol)
            XCTAssertEqual(got.connector.to.x, want.to.x, accuracy: mTol)
            XCTAssertEqual(got.connector.to.y, want.to.y, accuracy: mTol)
        }

        let structGap = try! XCTUnwrap(report.structureGaps[0])
        XCTAssertEqual(structGap.d, c.nearestStructure.d, accuracy: mTol)

        let equip = report.equipment[0]
        XCTAssertEqual(try! XCTUnwrap(equip.toPoolM), c.equipToPool, accuracy: mTol)
        XCTAssertEqual(try! XCTUnwrap(equip.toLotM), c.equipToLot, accuracy: mTol)

        XCTAssertEqual(try! XCTUnwrap(report.lotAreaM2), c.lotAreaM2, accuracy: 1e-4)
        XCTAssertEqual(site.poolFootprintM2, c.poolFootprintM2, accuracy: 1e-6)
        // Coverage rule is off in the example profile, but the measurement still reports.
        XCTAssertEqual(try! XCTUnwrap(report.coveragePct), c.coveragePct, accuracy: 1e-6)
        XCTAssertFalse(report.coverageViolation)
    }

    func testRound05() {
        for c in f.round05 {
            XCTAssertEqual(Geo.round05(c.x), c.rounded, accuracy: 1e-12, "x=\(c.x)")
        }
    }
}
